a:
  transitions:
    - suffix: :s1
      state:  :b
    - suffix: :s2
      state:  :b
    - suffix: :s3
      state:  :b
    - suffix: :s4
      state: :b
    - suffix: :s5
      state: :c
    - suffix: :s6
      state: :d
    - suffix: :s7
      state: :d
    - suffix: :s8
      state: :d
    - suffix: :s9
      state: :d
    - suffix: :s10
      state: :e
    - suffix: :s12
      state: :f
    - suffix: :s13
      state: :f
    - suffix: :s14
      state: :f
    - suffix: :s15
      state: :f
    - suffix: :s11
      state: :h

  final_state: false

b:
  transitions:
    - suffix: :s14
      state: :f

  final_state: true

c:
  transitions:
    - suffix: :s10
      state: :f
    - suffix: :s12
      state: :f
    - suffix: :s13
      state: :f
    - suffix: :s14
      state: :f

  final_state: true

d:
  transitions:
    - suffix: :s12
      state: :f
    - suffix: :s13
      state: :f

  final_state: false

e:
  transitions:
    - suffix: :s1
      state: :g
    - suffix: :s2
      state: :g
    - suffix: :s3
      state: :g
    - suffix: :s4
      state: :g
    - suffix: :s5
      state: :g
    - suffix: :s14
      state: :f
  final_state: true

f:
  transitions: []

  final_state: true


g:
  transitions:
    - suffix: :s14
      state: :f

  final_state: false

h:
  transitions:
    - suffix: :s14
      state: :f
    - suffix: :s1
      state: :g
    - suffix: :s2
      state: :g
    - suffix: :s3
      state: :g
    - suffix: :s4
      state: :g
    - suffix: :s5
      state: :g

  final_state: false

