# The order of the transitions is very crusial.
a:
  transitions:
    - suffix: :s16
      state: :c
    - suffix: :s7
      state: :k
    - suffix: :s3
      state: :h
    - suffix: :s5
      state: :h
    - suffix: :s1
      state: :l
    - suffix: :s14
      state: :f
    - suffix: :s15
      state: :g
    - suffix: :s17
      state: :e
    - suffix: :s10
      state: :e
    - suffix: :s19
      state: :m
    - suffix: :s4
      state: :h
    - suffix: :s9
      state: :c
    - suffix: :s12
      state: :f
    - suffix: :s13
      state: :b
    - suffix: :s18
      state: :d
    - suffix: :s2
      state: :h
    - suffix: :s6
      state: :h
    - suffix: :s8
      state: :b
    - suffix: :s11
      state: :b

  final_state: true

b:
  transitions:
    - suffix: :s3
      state: :h
    - suffix: :s5
      state: :h
    - suffix: :s1
      state: :l
    - suffix: :s4
      state: :h
    - suffix: :s2
      state: :h

  final_state: true

c:
  transitions:
    # Transitions to state K
    - suffix: :s7
      state: :k
    # Transitions to state H
    - suffix: :s6
      state: :h

  final_state: false

d:
  transitions:
    # Transitions to state F
    - suffix: :s14
      state: :f
    # Transitions to state E
    - suffix: :s10
      state: :e
    # Transitions to state B
    - suffix: :s13
      state: :b

  final_state: false

e:
  transitions:
    - suffix: :s7
      state: :k
    - suffix: :s3
      state: :h
    - suffix: :s5
      state: :h
    - suffix: :s1
      state: :l
    - suffix: :s4
      state: :h
    - suffix: :s18
      state: :d
    - suffix: :s2
      state: :h
    - suffix: :s6
      state: :h

  final_state: true

f:
  transitions:
    # Transitions to state K
    - suffix: :s7
      state: :k
    # Transitions to state D
    - suffix: :s18
      state: :d
    # Transitions to state H
    - suffix: :s6
      state: :h

  final_state: false


g:
  transitions:
    - suffix: :s5
      state: :h
    - suffix: :s3
      state: :h
    - suffix: :s1
      state: :l
    - suffix: :s4
      state: :h
    - suffix: :s18
      state: :d
    - suffix: :s2
      state: :h

  final_state: true

h:
  transitions:
    # Transitions to state L
    - suffix: :s1
      state: :l

  final_state: true

k:
  transitions: []

  final_state: true

l:
  transitions:
    # Transitions to state D
    - suffix: :s18
      state: :d

  final_state: true

m:
  transitions:
    - suffix: :s7
      state: :k
    - suffix: :s3
      state: :h
    - suffix: :s5
      state: :h
    - suffix: :s1
      state: :l
    - suffix: :s4
      state: :h
    - suffix: :s2
      state: :h
    - suffix: :s6
      state: :h

  final_state: true

