# The order of the transitions is very crusial.
a:
  transitions:
    # Transitions to state B
    - suffix: :s8
      state: :b
    - suffix: :s13
      state: :b
    - suffix: :s11
      state: :b
    # Transitions to state C
    - suffix: :s16
      state: :c
    - suffix: :s9
      state: :c
    # Transitions to state D
    - suffix: :s18
      state: :d
    # Transitions to state E
    - suffix: :s10
      state: :e
    - suffix: :s17
      state: :e
    # Transitions to state F
    - suffix: :s14
      state: :f
    - suffix: :s12
      state: :f
    # Transitions to state G
    - suffix: :s15
      state: :g
    # Transitions to state H
    - suffix: :s3
      state: :h
    - suffix: :s5
      state: :h
    - suffix: :s2
      state: :h
    - suffix: :s4
      state: :h
    - suffix: :s6
      state: :h
    # Transitions to state K
    - suffix: :s7
      state: :k
    # Transitions to state L
    - suffix: :s1
      state: :l
    # Transitions to state M
    - suffix: :s19
      state: :m

  final_state: true

b:
  transitions:
    # Transitions to state H
    - suffix: :s3
      state: :h
    - suffix: :s5
      state: :h
    - suffix: :s2
      state: :h
    - suffix: :s4
      state: :h
    # Transitions to state L
    - suffix: :s1
      state: :l

  final_state: true

c:
  transitions:
    # Transitions to state H
    - suffix: :s6
      state: :h
    # Transitions to state K
    - suffix: :s7
      state: :k

  final_state: false

d:
  transitions:
    # Transitions to state B
    - suffix: :s13
      state: :b
    # Transitions to state E
    - suffix: :s10
      state: :e

  final_state: false

e:
  transitions:
    # Transitions to state D
    - suffix: :s18
      state: :d
    # Transitions to state H
    - suffix: :s3
      state: :h
    - suffix: :s5
      state: :h
    - suffix: :s2
      state: :h
    - suffix: :s4
      state: :h
    - suffix: :s6
      state: :h
    # Transitions to state K
    - suffix: :s7
      state: :k
    # Transitions to state L
    - suffix: :s1
      state: :l

  final_state: true

f:
  transitions:
    # Transitions to state D
    - suffix: :s18
      state: :d
    # Transitions to state K
    - suffix: :s7
      state: :k
    # Transitions to state H
    - suffix: :s6
      state: :h

  final_state: false


g:
  transitions:
    # Transitions to state D
    - suffix: :s18
      state: :d
    # Transitions to state H
    - suffix: :s2
      state: :h
    - suffix: :s3
      state: :h
    - suffix: :s4
      state: :h
    - suffix: :s5
      state: :h
    # Transitions to state L
    - suffix: :s1
      state: :l

  final_state: true

h:
  transitions:
    # Transitions to state L
    - suffix: :s1
      state: :l

  final_state: true

k:
  transitions: []

  final_state: true

l:
  transitions:
    # Transitions to state D
    - suffix: :s18
      state: :d

  final_state: true

m:
  transitions:
    # Transitions to state H
    - suffix: :s2
      state: :h
    - suffix: :s3
      state: :h
    - suffix: :s4
      state: :h
    - suffix: :s5
      state: :h
    - suffix: :s6
      state: :h
    # Transitions to state K
    - suffix: :s7
      state: :k
    # Transitions to state L
    - suffix: :s1
      state: :l

  final_state: true

