protected_words:
  - abiye
  - adana
  - soyad
  - kedi
  - su

last_consonant_exceptions:
  - ad
  - arab
  - ked

vowel_harmony_exceptions:
  - saatler
  - alkoller

selection_list_exceptions:
  - su
  - ev
  - soyad
