protected_words:
  - abiye
  - adın
  - adana
  - akılsız
  - alaska
  - alet
  - ağda
  - ağız
  - alarm
  - altınbaşak
  - altınyıldız
  - anakucağı
  - anasayfa
  - anime
  - antifriz
  - araba
  - ardeşen
  - armanı
  - aroma
  - arma
  - arsız
  - asa
  - askı
  - astra
  - asus
  - atkı
  - ayakkabı
  - aynı
  - ayı
  - banka
  - başka
  - batık
  - bayı
  - belge
  - bellona
  - benten
  - benzin
  - beşinci
  - bilgi
  - bitki
  - boyut
  - branda
  - bütün
  - buzlu
  - çağrı
  - camsız
  - canta
  - çanta
  - çarşı
  - ceyiz
  - çıkış
  - çini
  - cımbiz
  - dalga
  - damla
  - derece
  - deniz
  - denim
  - dişli
  - düğün
  - ege
  - elbise
  - fendi
  - filtre
  - fıfa
  - fiyat
  - forma
  - gazete
  - gemi
  - görüntü
  - halı
  - igne
  - ince
  - internet
  - iyi
  - karyola
  - kayısı
  - kama
  - kadın
  - katı
  - killer
  - köşe
  - köse
  - kötü
  - kuma
  - kumanda
  - lamba
  - lazım
  - litre
  - mağaza
  - magaza
  - makara
  - makine
  - malzeme
  - mana
  - marka
  - masa
  - maskara
  - mine
  - mini
  - nine
  - numara
  - odun
  - oyun
  - ölçü
  - örgü
  - öykü
  - özen
  - parça
  - perde
  - pompa
  - pırlanta
  - raket
  - ranza
  - salı
  - şamdan
  - şapka
  - şifre
  - sunu
  - soyad
  - tabaka
  - takım
  - talımat
  - tarla
  - tasma
  - törpü
  - tozlu
  - tüplü
  - uçurtma
  - üfleme
  - ürün
  - ütü
  - uygun
  - uzatma
  - uzun
  - vana
  - vibe
  - yağlı
  - yapma
  - yardım
  - yasa
  - yıldız
  - zayıflama
  - zemin

last_consonant_exceptions:
  - ad
  - at
  - ked

vowel_harmony_exceptions:
  - alkoller
  - değerın
  - generali
  - generale
  - projektörlar
  - saatler
  - tabletlar
  - tersyüz
  - yaninda
  - yani

selection_list_exceptions:
  - al
  - am
  - aparat
  - ara
  - bilet
  - bisiklet
  - bulut
  - diyet
  - ev
  - es
  - fiyat
  - fırsat
  - general
  - git
  - gıt
  - iç
  - ip
  - internet
  - iyi
  - kağıt
  - kartuş
  - katı
  - kot
  - kötü
  - kumanda
  - lamba
  - mağaza
  - magaza
  - makara
  - makine
  - marka
  - maskara
  - ne
  - otomat
  - palet
  - perde
  - raket
  - ranza
  - robot
  - sepet
  - servis
  - soyad
  - su
  - tabaka
  - tablet
  - takım
  - talımat
  - tanıt
  - tarla
  - tasma
  - tenis
  - törpü
  - uç
  - uygun
  - var
  - yasa
