protected_words:
  - abiye
  - adana
  - soyad
  - kayısı
  - kedi
  - su
  - yıldız
  - zayıflama
  - zemin

last_consonant_exceptions:
  - ad
  - arab
  - ked

vowel_harmony_exceptions:
  - alkoller
  - saatler
  - tersyüz

selection_list_exceptions:
  - su
  - ev
  - soyad
